version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.13

jobs:
  test-code:
    <<: *defaults  
    steps:
      - checkout
      - restore_cache:
          keys:
          - v{{ .Environment.DEPENDENCY_CACHE_VERSION }}-dependencies-{{ checksum "package.json" }}
          - v{{ .Environment.DEPENDENCY_CACHE_VERSION }}-dependencies-
      - run: npm install
      - run:
          name: Run pre-commit actions
          command: npm run pre-commit
      - save_cache:
          paths:
            - node_modules
          key: v{{ .Environment.DEPENDENCY_CACHE_VERSION }}-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .

  integration-test:
    working_directory: ~/repo
    docker:
      - image: cypress/base:10.13
    steps:
      - checkout
      - restore_cache:
          keys:
          - v{{ .Environment.DEPENDENCY_CACHE_VERSION }}-dependencies-{{ checksum "package.json" }}
          - v{{ .Environment.DEPENDENCY_CACHE_VERSION }}-dependencies-
      - run: npm install
      - run:
          name: Run Integration test with Cypress
          command: npm run test-integration

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  deploy:
    jobs:
      - test-code
      - test-integration:
          requires:
            - test-code
      - deploy:
          requires:
            - test-integration
          filters:
            tags:
              only: /.*/
            branches:
              only: master
